name: Generate Snake

on:
  schedule: # 매일 실행
    - cron: "0 0 * * *" # UTC 시간대 기준, 매일 자정에 실행
  push: # 커밋이 푸시될 때 실행 (옵션)
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Generate Snake
        uses: Platane/snk@v2
        with:
          github_user_name: <your-username>
          outputs: dist/snake.svg

      - name: Push the Snake
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
